force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ToDoModel.cls
public with sharing class ToDoModel {

    public class SelectList{

        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;

        public SelectList(String label, String value){
            this.label = label;
            this.value = value;
        }

    }

    public class oModel{
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String category;
        @AuraEnabled
        public Datetime dueDate;
        @AuraEnabled
        public Datetime startDate;
        @AuraEnabled
        public String description;

        public oModel(Todo__c todo){
            this.id = todo.id;
            this.name = todo.Name;
            this.category = todo.Category__c;
            this.dueDate = todo.Due_Date__c;
            this.startDate = todo.Start_Date__c;
            this.description = todo.Description__c;
        }
    }
}