force-app/main/default/objects/Todo__c/Todo__c.object-meta.xml
<CustomObject>
    <label>Todo</label>
    <nameField>
        <label>Todo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Todo__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Car Service</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Todo__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ToDoService.cls
public with sharing class ToDoService {
    
    @AuraEnabled(cacheable=true)
    public static Object getCategoryPicklist(){
        ToDoModel.SelectList[] options = new ToDoModel.SelectList[]{};
        Schema.DescribeFieldResult fieldResult = Todo__c.Category__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple)
            options.add(new ToDoModel.SelectList(f.getLabel(), f.getValue()));
        return options;
    }

    @AuraEnabled(cacheable=true)
    public static Object getTodoList(){
        Todo__c[] todoLst = [SELECT Id, Name, Category__c, Due_Date__c, Start_Date__c, 
                                Description__c FROM Todo__c 
                                ORDER BY LastModifiedDate DESC];
        return getModelList(todoLst);
    }

    @AuraEnabled
    public static Todo__c createTodo(String todoString){
        ToDoModel.oModel todo = (ToDoModel.oModel) JSON.deserialize(todoString, ToDoModel.oModel.class);
        return persist(getTodo(todo));
    }

    static Todo__c getTodo(ToDoModel.oModel o){
        return new Todo__c(
            Name = o.name,
            Category__c = o.category,
            Due_Date__c = o.dueDate,
            Start_Date__c = o.startDate,
            Description__c = o.description
        );
    }

    static Todo__c persist(Todo__c sobj){
        upsert sobj;
        return sobj;
    }

    static ToDoModel.oModel[] getModelList(Todo__c[] todo_lst){
        ToDoModel.oModel[] mList = new ToDoModel.oModel[]{};
        for (Todo__c todo : todo_lst) {
            mList.add(new ToDoModel.oModel(todo));
        }
        return mList;
    }
}